name: ascii_art
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  gtk_window: ^0.1.1
  enough_ascii_art: ^1.1.0

flutter:
  uses-material-design: true

# add assets
  assets:
    - assets/figlet_fonts/

# add fonts
  fonts:
    - family:  'Agave'
      fonts:
        - asset: assets/fonts/agave.ttf